lookout/borderpatrol

.travis.yml
Modified .travis.yml accordingly and had Rob enable it for the lookout/borderpatrol (already enabled for wkimeria/borderpatrol and tested with this .yml)
https://travis-ci.org/wkimeria/borderpatrol/builds/46254437
=> Adding Travis CI Integration (changes to .travis.yml needed)

borderpatrol-core/src/main/scala/com/lookout/borderpatrol/AuthService.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/LoginFilter.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/Session.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/Secret.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/SessionId.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/Tokens.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/ExpiryComponent.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/Generator.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/Marshaller.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/SignerComponent.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/Types.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/id/package.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/package.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/secret/SecretStore.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/secret/SecretsWatcherApi.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/secret/package.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/store/SessionStore.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/tokens/TokenState.scala, borderpatrol-core/src/main/scala/com/lookout/borderpatrol/session/tokens/package.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/LoginFilterSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/SessionFilterSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/CryptoSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/SecretStoreSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/SecretsWatcherApiSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/SessionIdSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/SessionSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/SessionStoreSpec.scala, borderpatrol-core/src/test/scala/com/lookout/borderpatrol/session/TokensSpec.scala
This is a first try at some sane organization for a growing code base.
Hopefully, this will also help us test and see what tests are missing.
=> Cleanup and organize components

README.md
Line breaks were causing link generation errors
=> Fix links in README #45

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Tokens.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Access.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
This includes two commits for using a caching layer at the Access point.
=> Caching for ServiceTokens

README.md, auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala, bpConfig.json, core/src/main/scala/com/lookout/borderpatrol/Binder.scala, core/src/main/scala/com/lookout/borderpatrol/Manager.scala, core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala, core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala, example/src/main/scala/com/lookout/borderpatrol/example/Config.scala, example/src/test/scala/com/lookout/borderpatrol/example/ConfigSpec.scala
=> Use list of URLs for configuring hosts for all the upstream hosts

core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretsCache.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/EncoderSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SecretStoresSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
-Add a SecretsCache to handle secrets from Consul
-Add class ConsulConnection to connect and make requests to a Consul kv store
-Create json encoder for Secrets and consul kv store replies
-Add tests for new api class
For issue #40
=> Create a consul backed secret store api class and tests

README.md, bpConfig.json, build.sbt, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
- Also updated the README.md for secret and session store config
examples
- Add version to fat jar
Fixes #40
=> Add config to instantiate ConsulSecretStore

.central.synchro.sh, .gitignore, .travis.credentials.sh, .travis.yml, build.sbt
- Also enables auto-publishing via travis
Fixes #37
=> Publish releases to bintray and snapshots to jfrog

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala, bpConfig.json, build.sbt, core/src/main/scala/com/lookout/borderpatrol/Binder.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala, example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala, server/src/main/scala/com/lookout/borderpatrol/server/package.scala, server/src/main/scala/com/lookout/borderpatrol/server/services.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/ServicesSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/StatsdExporterSpec.scala
=> Add StatsdExporter for reporting metrics

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Credential.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala, bpConfig.json, build.sbt, core/src/main/scala/com/lookout/borderpatrol/Binder.scala, core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala, core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Access.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala, core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/BorderPatrolSuite.scala, core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/main/scala/com/lookout/borderpatrol/server/services.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/ServicesSpec.scala
- Fix support for multiple services with same subdomain
- Added CustomerIdentifier to represent customer specific config
Fixes #111
=> BP should match both subdomain and path to find Service

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, core/src/main/scala/com/lookout/borderpatrol/Binder.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala, server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala
It allows us to change per-logger log level from the admin interface
=> Use Twitter Logger for all the logs

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Tokens.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/TokensSpec.scala, build.sbt
Currently, MasterToken is mandatory, but in reality it should accept either of MasterToken or ServiceTokens
=> Fix tokens parsing for master and services

build.sbt, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
Added a couple of metrics and log messages
=> Add msg_source element to application/json response

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Credential.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala, build.sbt, core/src/main/scala/com/lookout/borderpatrol/Manager.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala
- Also, do not return error message back to caller
- Use X-Forwarded-Proto to determine if retdirect url should be
http or https
=> Cleanup logs and prep for v0.2.0 release

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagersSpec.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2Spec.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala, build.sbt, core/src/main/scala/com/lookout/borderpatrol/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/Manager.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/package.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/coreTestHelpers.scala
- anything else return 500
Fixes #153
=> User errors during authentication, redirect back to login page

.travis.yml, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokens.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala, build.sbt, core/src/main/scala/com/lookout/borderpatrol/HealthCheck.scala, core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Identity.scala, core/src/main/scala/com/lookout/borderpatrol/crypto/Cryptable.scala, core/src/main/scala/com/lookout/borderpatrol/crypto/EncryptedSessionStore.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/Secret.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/Session.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/package.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/EncoderSpec.scala, core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SecretStoresSpec.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, security/src/main/scala/com/lookout/borderpatrol/security/Csrf.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/HealthCheckServiceSpec.scala
Also, removed arganut and finch dependencies
Fixes #159, #44
=> Updated finagle version to 6.35.0, circe to 0.4.0, etc

build.sbt, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
=> If rewritten URL is empty, then insert "/" instead.

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2.scala, auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala, build.sbt, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
Log IP Address for security checks
=> Ip address Session Logs

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala, build.sbt, core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala, core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
- Replaced RewriteFilter to rewriteReq method
Fixes #171
=> Execute Rewrite op before shipping request to upstream service

build.sbt, core/src/main/scala/com/lookout/borderpatrol/sessionx/SignedId.scala
- fix exception raised due to change from apache codec to MIME encoder/decoder
=> Update to fiangle 6.36.0 version

README.md, bpConfig.json, build.sbt, example/src/main/scala/com/lookout/borderpatrol/example/ServerConfig.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, security/src/main/scala/com/lookout/borderpatrol/security/HostHeaderFilter.scala, security/src/main/scala/com/lookout/borderpatrol/security/SecureHeaders.scala, security/src/test/scala/com/lookout/borderpatrol/test/security/HostHeaderFilterSpec.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
Added HostHeaderFilter to verify that the request being serviced has either empty
or valid (entry is contained in the filters valid hosts set) host entry
=> Add support for validating host.

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala, auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala, core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/Errors.scala, core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala
- redirect user to login page on this error
- added logs on failure to lookup or decode session data
=> Treat BpOriginalRequestNotFound as a BpUserEror

build.sbt, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, security/src/main/scala/com/lookout/borderpatrol/security/HostHeaderFilter.scala, security/src/test/scala/com/lookout/borderpatrol/security/HostHeaderFilterSpec.scala
=> HostHeaderFilter checks for empty host and returns 400

build.sbt, core/src/main/scala/com/lookout/borderpatrol/sessionx/SignedId.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala, server/src/test/scala/com/lookout/borderpatrol/server/AccessLogFilterSpec.scala
Issue: #186 
Borderpatrol generates access logs.
=> Generate Access Logs

bpConfig.json, build.sbt, example/src/main/scala/com/lookout/borderpatrol/example/ServerConfig.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/AccessLogFilterSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
=> Make Access Logs configurable

build.sbt, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
Create log file directory if does not exist.
Issue: #193
=> Access Logs configuration.

bpConfig.json, build.sbt, example/src/main/scala/com/lookout/borderpatrol/example/ServerConfig.scala, example/src/main/scala/com/lookout/borderpatrol/example/service.scala, server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala, server/src/main/scala/com/lookout/borderpatrol/server/Config.scala, server/src/test/scala/com/lookout/borderpatrol/server/AccessLogFilterSpec.scala, server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
Allow output to file, stdout, stderr
Add fileCount parameter
Issue: #190
=> Allow Access logs to be optional

build.sbt, server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala
=> Rectify month field bug in access logs.

build.sbt, server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala, server/src/test/scala/com/lookout/borderpatrol/server/AccessLogFilterSpec.scala
=> Bug Fix - Log initial request by caching it and not modified request

build.sbt, security/src/main/scala/com/lookout/borderpatrol/security/SecureHeaders.scala, security/src/test/scala/com/lookout/borderpatrol/test/security/SecureHeadersSpec.scala
- Cors.HttpFilter is available in finagle framework
=> Remove CORS from SecureHeaderFilter and use Cors.HttpFilter instead

build.sbt
=> Apply Finagle update for memcached.
