lookout/borderpatrol

build.sbt
security/src/main/scala/com/lookout/borderpatrol/security/Csrf.scala
server/src/main/scala/com/lookout/borderpatrol/routers/ServiceMatchers.scala
server/src/main/scala/com/lookout/borderpatrol/routers/models.scala
server/src/main/scala/com/lookout/borderpatrol/routers/package.scala
server/src/test/scala/com/lookout/borderpatrol/routers/ServiceMatchersSpec.scala

This adds the "borderpatrol-server" module to the project that will
include all of the business logic for running borderpatrol as a server.
The service inference is determined by
1) path (e.g. /:service/rest/of/path)
2) subdomain (e.g. http://<service.?>.example.com)
If the path is "/" then it defaults to the "subdomain"
Ref: #52

Add routers for service inference

---

README.md
core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/package.scala
server/src/main/scala/com/lookout/borderpatrol/server/ServiceMatchers.scala
server/src/main/scala/com/lookout/borderpatrol/server/models.scala
server/src/main/scala/com/lookout/borderpatrol/server/package.scala
server/src/main/scala/com/lookout/borderpatrol/server/readers.scala
server/src/main/scala/com/lookout/borderpatrol/server/services.scala
server/src/test/scala/com/lookout/borderpatrol/server/ServiceMatchersSpec.scala

The build was failing because of missing implicits in server.readers,
this was just an oversight that wasn't caught because we have no tests
in server yet.
Further, server was misnamed as "routers", so this was changed.
Ref: #52

Fix build and update docs

---

README.md
build.sbt
docs/src/main/tut/Borderpatrol.md
project/plugins.sbt

Adds a /tut directory in project root to store markdown files.
Parses MD files and stores output in target/scala-N.NN/tut.
Refs: #2, #54

Add tut to parse markdown files

---

build.sbt
docs/src/main/tut/Borderpatrol.md

Borderpatrol.md had incorrect imports.  Also, re-arranged
docSettings to appear after tutSettings so that tut modifiers
could be called in the docSettings.
Refs: #2, #54

Fix tut compilation of markdown files

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Tokens.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Identity.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SessionStoreSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/reader.scala

This login filter will listen to the login service's POST and transform
the request into a IndentifyRequest[Credential] that Keymaster can
understand. Once Keymaster has succesfully provided the identity, that
identity is saved to a new session pointer and the user is redirected to
their original request location with a new cookie
It will also remove the old session, as it is no longer valid

Add LoginFilter for Keymaster

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala
security/src/main/scala/com/lookout/borderpatrol/security/Csrf.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/CsrfSpec.scala

This commit provides upstream services with a way to do CSRF without
needing to be stateful themselves. Instead, they need only communicate
with Border Patrol via two options:
- Header (useful for javascript single page apps)
- Query parameter (useful for all others)
Upon successful login, the user should be presented with a CSRF cookie
whos value upstreams will use to inject into requests for Border Patrol
to verify that there is no CSRF vulnerability. This pattern is known as
Double Submit Cookie.
The request will be routed through Border Patrol which will inspect both
the header or param, and the cookie value that each matches. Since we
use the capabilities of the SessionId, we also get the cryptographic
attributes in this CSRF cookie.
Once Border Patrol has verified the incoming CSRF …

Add CSRF protection filter

---

README.md
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Tokens.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/TokensSpec.scala
bpConfig.json
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/crypto/Signer.scala
core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala
example/src/main/scala/com/lookout/borderpatrol/example/Config.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
serviceids.json

Also:
- rename identityProvider, loginProvider, accessProvider, etc to identityManager,
loginManager, accessManager, etc
- Move keymasterIdentityProvider service chain and keymasterAccessIssuer service
chain to keymaster (common) code.
- Add Binders to dynamically bind to upstream or identity or access or login
service on the fly.
- Modify ServiceIdentifier to include loginManager and hosts.
- Modify ServiceMatchers to match subdomain first and then match the
serviceIdentifier path or loginManager paths.

Use json for entire config and validate the configuration

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/crypto/CryptKey.scala
core/src/main/scala/com/lookout/borderpatrol/crypto/Signer.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Secret.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Session.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionId.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Tag.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Types.scala
core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/crypto/cryptoSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/EncoderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SessionIdSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SessionSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SessionStoreSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/TagSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/CsrfSpec.scala

- Detect if Session (i.e. user) is authenticated or not from the SessionId
(i.e. added a new byte inside Sessionid)
- If SessionId is authenticated, then any HTTP requests to LoginManager paths
(i.e. unauthenticated paths) should be redirected to the protected
Service endpoint (i.e. path of the ServiceIdentifier)
- If SessionId is not authenticated (i.e. not tagged), then any HTTP requests
to protected endpoint paths, should be redirected to LoginManager path
Fixes #85

Added BorderFilter to detect if session is tagged i.e. authenticated or not

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
bpConfig.json
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
server/src/test/scala/com/lookout/borderpatrol/server/ServicesSpec.scala

- ProtoManager contains seperate config for each protocol
(such as internal keymaster specific or OAuth2 or SAML)
Fixes #93

Add ProtoManager for protocol specific config

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
bpConfig.json
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
server/src/test/scala/com/lookout/borderpatrol/server/ServicesSpec.scala

Its an optional parameter
If present, it will replaces the external path configuration in
ServiceIdentifier with the rewritePath configuration in the ServiceIdentifier
Fixes #103

Add rewritePath to ServiceIdentifier

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionId.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/services.scala

- simply listens for logouts on a hardcoded path `/logout`
- if Request contains the cookie for `SessionId`, then the Session is looked up and removed from the SessionStore
- The client is redirected to default Service Id dictated by the subdomain (i.e. configured in customerIdentifier)
Fixes #114

Add logout support

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/package.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala

* Post login, BP should return 404 for unknown resources
* Pre login, BP should redirect requests (with valid or invalid paths) to login page
* And in all cases should redirect Root path to default Service
Fixes #120

After login return 404 for unknown resources

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
bpConfig.json
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala
core/src/test/scala/com/lookout/borderpatrol/test/BinderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SecretStoresSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
server/src/test/scala/com/lookout/borderpatrol/server/StatsdExporterSpec.scala

- Checkpoint, ErrorRedirect, logout all become unprotected upstream services
- Remove LoginManagerBinder (it doesn’t connect to upstream anymore)
- Remove LoginManagerFilter (replaced by unprotectedServiceChain inside BorderService)
- Moved alternate constructor for StatsdExporter to object (so that we can avoid the new)
Also:
- Fixed afterEach to call super
- Fixed ConsulSecretStore to use HashWheeledTimer instead of DefaultTimer.twitter (deprecated)
- Fixed SecretStoreSpec to close the timer
- Cleaned up BinderSpec
Fixes #123

Add support for unprotected upstream services

---

bpConfig.json
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

port - port where each BP node anchors
external endpoint - visible to outside work; E.g. ELB address (and port if necessary)
loggedOut url - after a logout, user is redirected to this URL (in order to add a landing area after SSO logout)

Add config for port, external endpoint, loggedOut url

---

bpConfig.json
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

Backout the `externalEndpoint` configuration, because external subdomain will be different for each tenant. Instead we should keep relying on `req.host`; but we eventually need to resolve what protocol (http or https) to use for redirect.

Backout externalEndpoint changes committed by pull request 125

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Credential.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
build.sbt
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

Currently, config validation stops at first error. Instead we should display
all the errors at once, for better experience.
Also, error messages are vague (i.e. failed to decode following fields:
CustomerIdentifier). It should display actual error message that caused the parsing
failure (albeit in some cases).
Fixes #127

Show all config validation errors at once

---

auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/TokensSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/ServiceMatcher.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala

- Split into IdentityService, AccessIssuer and UnprotectedService filters
- Allow POST to loginConfirm w/o sessionId to continue with authentication
Fixes #130

Split BorderService into seperate filters

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Tokens.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/TokensSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/Errors.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Identity.scala
core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala
core/src/main/scala/com/lookout/borderpatrol/crypto/Cryptable.scala
core/src/main/scala/com/lookout/borderpatrol/package.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Encoder.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Errors.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/Session.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SignedId.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/EncoderSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SignedIdSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/main/scala/com/lookout/borderpatrol/server/Errors.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

- Added prefix "Bp" to all the BP errors/exceptions
- Throw Bp exceptions for all the error responses generated by BP2
- Convert exceptions to error responses in the ExceptionFilter
- If request is exepcting an application/json response, then return
a response with custom response (e.g. contains a redirect_url)

Add support for application/JSON calls in BP2

---

auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Binder.scala
core/src/main/scala/com/lookout/borderpatrol/HealthCheck.scala
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala
core/src/main/scala/com/lookout/borderpatrol/auth/OAuth2.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala
core/src/test/scala/com/lookout/borderpatrol/test/HealthCheckSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/OAuth2Spec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
security/src/main/scala/com/lookout/borderpatrol/security/Csrf.scala
security/src/main/scala/com/lookout/borderpatrol/security/SecureHeaders.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala
server/src/test/scala/com/lookout/borderpatrol/server/StatsdExporterSpec.scala

- Add labels to connection metrics (it makes metrics readable)
- Fix CustomerIdFilter, SessionIdFilter and AccessFilter to reduce the handle time
(i.e. time to setup the futures in the filter chain, i.e. time consumed by a
thread to process the incoming request; reduced from 800 us to 150 us)
- Fix StatsdExporter to report all the stats in a single DatagramPacket, instead
of multiple writes

Add labels for connection metrics and perf fixes

---

README.md
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Manager.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/util/Helpers.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/helpers.scala
core/src/test/scala/com/lookout/borderpatrol/test/util/HelpersSpec.scala
security/src/main/scala/com/lookout/borderpatrol/security/Csrf.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/CsrfSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

- since it fetches query param from uri (GET) or contentString (POST)
Also,
- Log an error message if we see multiple ServiceIdentifiers for a
tuple of (service name and protected flag.

Use Request ParamMap instead of req.uri

---

.travis.yml
README.md
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala

Also,
- if user attempts goto login page directly, then after authentication, redirect it to default service
- removed some of the benign operations executed in the Future contexts

Use destination as a query param, instead of target_url

---

README.md
auth/src/main/scala/com/lookout/borderpatrol/auth/keymaster/Keymaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/keymaster/KeymasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala

- Instead add methods to create appropriate response objects.
- This broke the CsrfInsertFilter, as the exception bypassed the
filter.
Fixes #142

Remove BpRedirectError and BpLogoutError

---

build.sbt
example/src/main/scala/com/lookout/borderpatrol/example/ServerConfig.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

- The LoginManager is a base class for differnet auth types
- Currently only 2 types (base and oauth2) are defined in this repository
- The app (e.g. example app in this case) can add more types
- To do so moving implicit base encoder and decoder to example

Move LoginManager's encoder-decoder to example

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
server/src/main/scala/com/lookout/borderpatrol/server/StatsdExporter.scala
server/src/test/scala/com/lookout/borderpatrol/server/StatsdExporterSpec.scala

- A quick pull request to fix metric type for StatsdExporter. 
- location had some sensitive information when it comes to oAuth2; so trim all the query parameters

Fix metric type and do not print query params in location in log

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/ServerConfig.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

- it allows example to be innovative and create different objects
for a given same base class of Endpoint and LoginManager
- also fixed handling Exception with noMessage (causes null pointer
exception in LogFormatter)

Move Endpoint and LoginManager config to example

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagersSpec.scala
build.sbt

If `action=consent`, then AAD redirect contains `prompt=admin_consent`. This is typically necessary, when AAD admin provides access to apps for AAD non admins

Add action query param to request consent during AAD auth

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/Endpoint.scala
core/src/test/scala/com/lookout/borderpatrol/test/EndpointSpec.scala

In such scenarios, we typically assume that single host is going to be ELB.
Also restored nimbus version back to 4.7 for compatibility.

Disable failfast if single host is configured on a endpoint

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/Identity.scala

When user login fails due to user error, then user is redirected back to login page. Currently, the redirect location contains query param to indicate failure message. Intent of this fix is to change this error message to a http status code

On user error, redirect with error code instead of error message as query param

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala

Forbidden requests to Borderpatrol to be routed to forbidden page instead of login page.

Re-route forbidden requests to Borderpatrol

---

build.sbt
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala

The main intention of this fix is to ensure that when a node from the list goes down (as determined by FailureAccrualPolicy), the node is removed from the list, so that failures can be contained. The node is marked dead for 60 seconds. After that timeout, the node will start probing. If down, we may experience additional failure, but node will be again marked as dead. However, if node is up, the probing will succeed and node will be back into the service.

Fix memcached client config. Enable evict and setup failure accrual policy

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala

Update the mock to process the json content. Also, updated the formatRedirectResponse code to take `msgSrc` as an optional input

Fix mock services to handle content in json format

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/Errors.scala
security/src/main/scala/com/lookout/borderpatrol/security/HostHeaderFilter.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/HostHeaderFilterSpec.scala

Resolve conflicts ensued by 180 and 181.
After successful authentication, if we fail to find that Original Request, then redirect user back to default service. That's a more resilient fix.

Move canned response to a val and bump up version

---

.travis.yml
build.sbt
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
security/src/main/scala/com/lookout/borderpatrol/security/SecureHeaders.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/SecureHeadersSpec.scala

Add CORS support. Update tests for specific expectations - such as overriding params in response and presence of CORS params in response.

Add support for pushing CORS headers in response

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagersSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/util/Helpers.scala
core/src/test/scala/com/lookout/borderpatrol/test/util/HelpersSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala

- also allow "space" in the query param
Fixes #184

Log and return 403, in case AAD returns anything other than oAuth2 code

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/auth/DestinationValidator.scala
core/src/main/scala/com/lookout/borderpatrol/util/Helpers.scala
core/src/test/scala/com/lookout/borderpatrol/test/DestinationValidatorSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/util/HelpersSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
security/src/test/scala/com/lookout/borderpatrol/test/security/SecureHeadersSpec.scala

Push changes to check if host name for a "destination" is allowed.
Caller can proceed on action with value obtained from DestinationValidator
Fixes #188

If destination query param is URL, then validate that host belongs to Set of valid hosts

---

auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2.scala
auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/Tokenmaster.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/OAuth2Spec.scala
auth/src/test/scala/com/lookout/borderpatrol/auth/tokenmaster/TokenmasterSpec.scala
build.sbt
core/src/main/scala/com/lookout/borderpatrol/Endpoint.scala
example/src/main/scala/com/lookout/borderpatrol/example/BorderPatrolApp.scala

Also,
- using null tracer (disable zipkin)
- Use default port if no port specified in the URL

Consolidated and updated AAD token access methods

---

build.sbt
core/src/main/scala/com/lookout/borderpatrol/Endpoint.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
example/src/main/scala/com/lookout/borderpatrol/example/service.scala
server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala

Also,
- remove methods from RoutingService
- Disable failfast if upstream is ELB
- Synchronize the Endpoint cache to ensure only 1 instance of Client
created per endpoint

Add OptionsFilter to handle HTTP OPTIONS request

---

bpConfig.json
build.sbt
core/src/main/scala/com/lookout/borderpatrol/ServiceIdentifier.scala
core/src/main/scala/com/lookout/borderpatrol/auth/BorderAuth.scala
core/src/main/scala/com/lookout/borderpatrol/sessionx/SessionStore.scala
core/src/test/scala/com/lookout/borderpatrol/test/ServiceMatcherSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/auth/BorderAuthSpec.scala
core/src/test/scala/com/lookout/borderpatrol/test/coreTestHelpers.scala
core/src/test/scala/com/lookout/borderpatrol/test/sessionx/SessionStoreSpec.scala
server/src/main/scala/com/lookout/borderpatrol/server/AccessLogFilter.scala
server/src/main/scala/com/lookout/borderpatrol/server/Config.scala
server/src/test/scala/com/lookout/borderpatrol/server/ConfigSpec.scala

- Currently service can be either defined as protected or unprotected. But
thats not sufficient, as each service may have one or more such paths (pockets)
- By default the anchor path would be protected
- A set of unprotected paths, if specified, will create the necessary holes

Allow one or more unprotected paths on the main anchor path
